// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuOm0tG8GvgHXyM6tzCtHEUF1YzagPtgI',
    appId: '1:22338640474:web:348b5bc73f6d7844d05663',
    messagingSenderId: '22338640474',
    projectId: 'fluttertarde',
    authDomain: 'fluttertarde.firebaseapp.com',
    storageBucket: 'fluttertarde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmVecpeVcaMP3TNnDyqH1C8aukXZQ8MXs',
    appId: '1:22338640474:android:898e5d1a132b6b54d05663',
    messagingSenderId: '22338640474',
    projectId: 'fluttertarde',
    storageBucket: 'fluttertarde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx1dpiIA-qibJEvxCs7EU79M-MNzwwsv0',
    appId: '1:22338640474:ios:b2b40fd0d7c735c5d05663',
    messagingSenderId: '22338640474',
    projectId: 'fluttertarde',
    storageBucket: 'fluttertarde.appspot.com',
    iosBundleId: 'br.com.dtec.loja2.flutterdart10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx1dpiIA-qibJEvxCs7EU79M-MNzwwsv0',
    appId: '1:22338640474:ios:b2b40fd0d7c735c5d05663',
    messagingSenderId: '22338640474',
    projectId: 'fluttertarde',
    storageBucket: 'fluttertarde.appspot.com',
    iosBundleId: 'br.com.dtec.loja2.flutterdart10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuOm0tG8GvgHXyM6tzCtHEUF1YzagPtgI',
    appId: '1:22338640474:web:eaa458bbd170d807d05663',
    messagingSenderId: '22338640474',
    projectId: 'fluttertarde',
    authDomain: 'fluttertarde.firebaseapp.com',
    storageBucket: 'fluttertarde.appspot.com',
  );
}